### ISSUE TITLE
Problem with configuration  & conversation sharing

### ISSUE THREAD

**Issue by crkrenn** [pol-is/polis-issues#109]
I have polis running on Ubuntu, with polisServer, polisClientAdmin, polisClientParticipation, and polisMath running in 4 separate xterminals. I can create new users with "http://localhost:5002/createuser". I can create new conversations from "http://localhost:5002".

But, when I try to distribute/share that conversation with other users, the sharing url (e.g. http://localhost:5002/42pmrr2nkt) only displays a blank screen. http://localhost:5002/inbox also displays a blank screen. 

There are no smoking guns that I can determine in either the console logs or via attaching to the node processes with Chromium. 

The following messages may provide a clue:

info getComments undefined
info thecontext undefined

pool.replica.undefined acquire client begin
pool.replica.undefined acquire client
pool.replica.undefined release client

Is there some global context or initiation that I am missing?

Gratefully and sincerely, 

-Chris

info /api/v3/conversations {}
part2
{}
{ host: 'localhost:5000',
  'user-agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0',
  accept: '*/*',
  'accept-language': 'en-US,en;q=0.5',
  'accept-encoding': 'gzip, deflate',
  referer: 'http://localhost:5002/',
  'x-requested-with': 'XMLHttpRequest',
  cookie: '__stripe_mid=38692f4f-6231-448a-8db3-34039f73a28b; pc=wrzBDsukDI6pCct3P642; intercom-lou-nb5hla8s=1; token2=ZzL4QtA4U94WTElrfn25; uid2=1; e=1; uc=1518976011004; plan=1',
  connection: 'keep-alive',
  'if-none-match': 'W/"325c-rdbcRVUFWAAtODrt06VXgg"',
  origin: 'http://localhost:5000' }
authtype doCookieAuth
info thecontext undefined
pool.replica.undefined acquire client begin
pool.replica.undefined acquire client
pool.replica.undefined release client
pool.replica.undefined acquire client begin
pool.replica.undefined acquire client
pool.replica.undefined release client
pool.replica.undefined acquire client begin
pool.replica.undefined acquire client
pool.replica.undefined release client
info heapUsed: 44863552 heapTotal: 50434048 rss: 79650816

**Comment by metasoarous** [comment]
Actually, all the requests should go through polisServer, not polisClientAdmin. So that would probably be the http://localhost:5000 url. Note that you'll want to make sure that the `DEV_MODE=true` env variable is set, or it will try to redirect you to https.

**Comment by crkrenn** [comment]
Thanks very much! One of two things solved the problem: 1) updating
polisClientParticipation/polis.config.js to the current repo template, or
2) replacing polisClientParticipation/webpack.config.js with
webpack.config.dev.js. I'm guessing pol-is/polisServer#96 was the most important.

To avoid this problem for others, I would suggest to "git mv
webpack.config.js webpack.config.prod.js". Would you accept a PR for that?

Now, I need to insert the conversation_translations into the polis database
because I created my original polis database in the fall. It would be nice
to have the database updating more automated, but I imagine it is not a
high priority.

**Comment by metasoarous** [comment]
I think for starters I'd be happy to take a PR clearing up this issue in the docs. I'd consider a `git mv` PR, but maybe open an issue on that first in case there are any issues; It's possible we might break something for someone by making that move.

Actually, smoother database setup and maintenance is kind of a priority right now (e.g. pol-is/polisServer#192), as we're looking to sanely Dockerize things. So if you'd like to issue/PR on this, I'd encourage you to do so.

**Comment by crkrenn** [comment]
I think I have a solution for my particular problem using
http://www.sql-workbench.eu/ which will generate the postsql code to update
a database to match a newer schema. I've created the sql code, but want to
back up the database before running it. If it works, I can post details.

Longer term, maybe something like
https://github.com/mbryzek/schema-evolution-manager could be helpful.

**Comment by metasoarous** [comment]
Mmm... this seems like a separate issue. There are clearly some missing pieces to the db schema story, but I think the right way to approach that is to focus on writing the appropriate migrations. I recall that there were some issues with the schema not being fully up to date, but we should open a separate issue for that I think. I would love a PR resolving that issue.

**Comment by patcon** [comment]
I believe the schema is now up-to-date, so closing, but pls speak up if it should be re-opened (also happy to help re-ticket lingering todos from this) 🙂
