### ISSUE TITLE
polisClientParticipation deployPreprod

### ISSUE THREAD

**Issue by crkrenn** [pol-is/polis-issues#118]
Hello again, 

I'm trying to use "deployPreprod" to upload static content from polisClientAdmin to S3, but have been unsuccessful. 

I created a bucket on s3 and updated "S3_BUCKET_PREPROD" in polis.config.js. I set UPLOADER to 's3'. I entered my credentials in ".polis_s3_creds_client.json"

function "s3uploader" in gulpfile.js does get called, and aws creds are read from .polis_s3_creds_client.json, but "s3(creds, oo)" does not seem to be working, and there are no useful error messages. 

To try to debug this, I wrapped the s3(creds,oo) call with console.log calls. They work as expected before the s3 call, but are not executed after the s3 call. After reading the gulp-s3 man page, I tried both s3(creds) and s3(creds, oo), but neither solved the problem. 

I'm running with the current prod branch (1/28/19) of polisClientParticipation. My aws creds worked with the aws cli. 

Attached below is an excerpt of my edited gulpfile.js file and a sample console.log output. 

What should I try next? Is there a way to turn on more verbose error logging for gulp-s3?

Gratefully, 

-Chris

Code excerpt of edited gulpfile.js:

        console.log("about to call s3");
        //console.log("stringify creds:");                                     
        //console.log(JSON.stringify(creds));                                  
        console.log("stringify oo:");
        console.log(JSON.stringify(oo));
        var myResult = s3(creds, oo);
        //var myResult = s3(creds);                                            
        console.log("finished calling s3");
        console.log("myResult: " + JSON.stringify(myresult));
        return myResult;

Console.log output: 

  ~/polis/polisClientParticipation$ ./deployPreprod
  Running node v6.2.0 (npm v3.8.9)
  Uploader: s3
  getGitHash begin
  (node:2703) DeprecationWarning: sys is deprecated. Use util instead.
  done setting destRoot: dist/cached/2019_1_28_23_13_37_628baae  destRootRest: 
  cached/2019_1_28_23_13_37_628baae  destRootBase: dist
  [23:14:12] Version: webpack 1.15.0
          Asset    Size  Chunks             Chunk Names
  vis_bundle.js  984 kB       0  [emitted]  main
  /home/restic/polis/polisClientParticipation/js/templates/plan-upgrade.handlebars
  /home/restic/polis/polisClientParticipation/js/templates/settings.handlebars
  /home/restic/polis/polisClientParticipation/js/templates/settingsEnterprise.handlebars
  dist/cached/2019_1_28_23_13_37_628baae
  doDeployBatch [ 'dist/cached/2019_1_28_23_13_37_628baae**/**',
    '!dist/cached/2019_1_28_23_13_37_628baae/js/**' ]
  about to call s3
  stringify oo:
  {"delay":1000,"subdir":"cached","headers":{"x-amz-acl":"public-read","Cache-Control":"no-transform,public,max-age=31536000,s-maxage=31536000"}}
  doDeployBatch [ 'dist/cached/2019_1_28_23_13_37_628baae**/css/**' ]

**Comment by crkrenn** [comment]
I’m having similar problems with polisClientAdmin,although “aws s3 cp” works fine with the same creds.  Could someone please explain the file structure of the preprod.pol.is s3 bucket so I can generate it with another tool? In particular, how are the clientAdmin and clientParticipation files segregated and served?

Thanks again!

C.

**Comment by crkrenn** [comment]
I've solved the problem by using deployPreprod with scp to localhost, then "aws s3 sync" to move that to s3. 

I'm happy to debug the s3 if it is helpful and if anyone else has this problem. Otherwise, this issue probably can be closed. 

Gratefully, 

-Chris

**Comment by colinmegill** [comment]
Thanks @crkrenn

**Comment by metasoarous** [comment]
Hi @crkrenn. Thanks for reporting this.

I'm glad you for a workaround, but it would be nice to properly resolve the issue if you have fresh eyes and bandwidth to look at this. At the very least, I can tell you that we deploy with S3, and while we don't frequently deploy changes to the participation client, the last time I did was just a few months ago, and nothing in the deploy stack has changed since then.

If nothing like going over credentials again to look for a typo turns up anything, may I ask whether you've tried running the `deploy_TO_PROD` script?

Thanks again for your time.

**Comment by patcon** [comment]
@metasoarous given that we have a docker env working, do you feel this is worth keeping open?

**Comment by crkrenn** [comment]
I have a solution in progress and plan to contribute to monorepo when possible.
