### ISSUE TITLE
configuration file for buildNumber?

### ISSUE THREAD

**Issue by crkrenn** [pol-is/polis-issues#119]
Hello again, 

I am having trouble figuring out where and how "buildNumber" is defined for polisServer.

I know how it is generated in the polisClient*/gulpfile.js:

`  var unique_token = [d.getFullYear(), d.getMonth() + 1, d.getDate(), d.getHours(), d.get
Minutes(), d.getSeconds(), hash].join("_");`

And, polisSever gets it from "req.query.build":
`     buildNumber = req.query.build;`

But I don't see how req.query.build is set. (And, there is no "build" field in db_setup_draft.sql.)

Could someone please help?

Gratefully, 

-Chris

PS. It is clearly working for the current pol.is deployment:

https://pol.is/cached/2018_3_2_13_17_16_f837ad8/js/admin_bundle.js

**Comment by crkrenn** [comment]
I am still curious about this, but I don't think it is related to my problem in deploying polis with a remote STATIC_FILES_HOST. The correct directories are embedded in the preprod root html files: 

parallels@ubuntu:~/scp_dir2/preprod$ grep -e cached *html
index_admin.html:    <script src="/cached/2019_2_3_20_30_45_77afef1/js/admin_bundle.js"></script>

**Comment by metasoarous** [comment]
For the record, I think `req.query.build` is coming through from the client request, so this is probably just the build of whatever client is submitting the request. I think the only reason we use this in `server.js` is to log out what clients are accessing the app, so we know if someone is using a stale client for some reason.

![image](https://user-images.githubusercontent.com/88556/53325623-4f0fa580-3916-11e9-8c99-47c0dbd98d8d.png)

Thanks as always for kicking the tires and asking questions.
