### ISSUE TITLE
Show degree of consensus across all comments in convo

### ISSUE THREAD

**Issue by colinmegill** [pol-is/polis-issues#17]
There are three strains of thought here...

* pol.is should grow into showing insights into 'all' comments in a number of ways, but not do so in list form because skimming means no data collection
* pol.is should offer a snapshot view of how divided a conversation is
* pol.is should better handle the special case of 'everyone agrees with each other on everything'

A distribution of % voted same way is one way to do this. Keep in mind that absolute consensus could also mean 100% disagreement.

![image](https://cloud.githubusercontent.com/assets/1770265/20941158/1c147d7c-bbaa-11e6-919a-5aab12a8a1b7.png)

Thus this one:

https://pol.is/2jruxfaxzc

Shows up quite differently than:

https://pol.is/3phdex2kjf

**Comment by colinmegill** [comment]
A possible alternative, with consensus at each end:

![image](https://cloud.githubusercontent.com/assets/1770265/20941772/e18ef53a-bbac-11e6-9f21-56b914bc03d6.png)

**Comment by patcon** [comment]
@colinmegill this looks maybe like what is shown in the report app.

If so, can we close? And further, are there any lingering aspects of this that you'd like to spawn new issues for as we close?

**Comment by colinmegill** [comment]
This can be closed, it is further explored in notebooks which will be
integrated into the report.

Thanks @patcon
