### ISSUE TITLE
Crowd moderation v0.0.1

### ISSUE THREAD

**Issue by colinmegill** [pol-is/polis-issues#26]
Crowd moderation in pol.is will be implemented as additional buttons that replace the primary agree disagree or pass buttons after they are clicked, without replacing the comment text. The tentative proposal for those options are as follows:

* Agree
  * This is important
  * This is a fact
  * I feel this way
* Disagree
  * Not my feeling
  * Not fact
  * Abusive 
* Pass
  * Unsure
  * Spam
  * Abusive

With the option to skip. Uncertain at this point whether we allow multiselect. An initial UI sketch:

![crowdmod](https://cloud.githubusercontent.com/assets/1770265/21075498/8f38f3ca-bec8-11e6-80fb-b0d6f42c54e9.png)

Crowd moderation will not always appear. Here are some thing that could affect when it is shown.

First, there could be a minimum threshold of comments for crowd moderation to be shown at all. There could also be a switch to turn it on and off in configuration. If, for instance, there are only seed comments, we shouldn't be asking whether they are abusive. It might be useful to ask whether or not they are unclear. 

It is also the case that even when crowd moderation is 'on', it will not be shown after every comment. It will be shown more if people interact with it, and less if they choose to skip it before making a selection. Thus people self select / opt into more work.

**Comment by patcon** [comment]
> If, for instance, there are only seed comments, we shouldn't be asking whether they are abusive.

Why not? I think to add a special edge-case for seed comments is to hold your conversation admins in too high regard. They're not all going to be consultation professionals ;)

**Comment by patcon** [comment]
Yay! You guys pushed this, huh? I ran into it the first time when I was demo'ing with that Toronto city staff person last night, and got excited and a little flustered as I figured out how to best demo it on-the-fly ;)

**Comment by colinmegill** [comment]
@patcon were you demo-ing on preprod?

cc @mbjorkegren

**Comment by mbjorkegren** [comment]
@patcon We did push it briefly, but we hit a QA issue and had to revert it. It'll be live again soon.

**Comment by patcon** [comment]
cool! no worries. thx :)

**Comment by patcon** [comment]
Just to follow-up: is this official retired as a planned feature? If so, is there any context you could offer as to why, in case anyone running their own instance is tempted to re-enable the codepath that I think is still functional here:

https://github.com/pol-is/polisServer/blob/806e77e508cd8c27a8c372502c111359fdd8b28e/server.js#L9072

Uncommenting this line makes it so that every vote is followed by a crowd moderation prompt like so:
<img width="868" alt="Screen Shot 2020-04-28 at 5 46 07 PM" src="https://user-images.githubusercontent.com/305339/80536500-d9b7be80-8978-11ea-91f3-303c10a601b1.png">

**Comment by patcon** [comment]
Hm. Seems to not be populating database table `crowd_mod` -- not sure why:

```
polis-dev=# SELECT * FROM crowd_mod;
 zid | pid | tid |    created    | as_important | as_factual | as_feeling | as_notmyfeeling | as_notgoodidea | as_notfact | as_unsure | as_spam | as_abusive | as_offtopic
-----+-----+-----+---------------+--------------+------------+------------+-----------------+----------------+------------+-----------+---------+------------+-------------
   1 |   2 |   2 | 1588106782742 |              |            |            |                 |                |            |           |         |            |
   1 |   2 |   0 | 1588108892289 |              |            |            |                 |                |            |           |         |            |
(2 rows)

polis-dev=#
```

**Comment by colinmegill** [comment]
Abandoned in favor of comment routing. There's no way to implement crowd moderation without the potential for participants to overload it to punish the ideas they disagree with algorithmically.

**Comment by colinmegill** [comment]
Perhaps _no way_ to do it goes too far — but the role of a central moderator, assumed to be an ethical / trusted counterparty to the participants, continues to be a core assumption of the system. 

In the cases where no central moderator is available or desired, comment routing is enough to make good use of participants' time even if there's some garbage in the system.

**Comment by colinmegill** [comment]
It can be noted that pol-is/polis-issues#123 avoids some of these problems by asking the user when a comment is significant to them, without asking them to 'downvote' others.

**Comment by patcon** [comment]
Ok, thanks! So should we leave the code in there for a future context/reckoning, or strip it out?

**Comment by colinmegill** [comment]
At the _moment_ the system is in too much flux to remove code. Feel free to
flag it for removal. Once we're on a steady pace of deployment and
integration tests we can begin pruning bit by bit.
