### ISSUE TITLE
Port open issues from other repos

### ISSUE THREAD

**Issue by patcon** [pol-is/polis-issues#4]
Love the idea of having one main issue repo. Having said that, can someone manually port issues from the other repos. I recall that there were a few I cared about -- obviously my own, but I think some others. Buuuttt can't remember them... ;)

**Comment by mbjorkegren** [comment]
Haha don't worry, I took screenshots, I'll get those posted soon.

**Comment by patcon** [comment]
Heh this is no longer relevant after old issue queues were reactivated :)
