### ISSUE TITLE
clarify why the Submit button is disabled when comment is too long

### ISSUE THREAD

**Issue by mbjorkegren** [pol-is/polis-issues#56]
The red negative number doesn't work for some people.

**Comment by mbjorkegren** [comment]
e.g. 140 characters available, you've used 32 characters too many

**Comment by patcon** [comment]
Alternative pattern for consideration:
- show char count (with red)
- don't gray-out the submit button
- flash the verbose msg message when ppl try to submit

Seems most sensible if there are other msgs that might want to be flashed, but not sure if that's the case

**Comment by patcon** [comment]
woooo this is now done. closing

<img width="904" alt="Screen Shot 2020-05-03 at 11 14 38 PM" src="https://user-images.githubusercontent.com/305339/80932040-e2066400-8d93-11ea-913c-d45c9f9b7fcd.png">
