### ISSUE TITLE
Auto-translate comments into reader's language

### ISSUE THREAD

**Issue by patcon** [pol-is/polis-issues#7]
Most likely using the Google Translate API, or some other service.

Note: The UI itself has already been translated to [some languages](https://github.com/pol-is/polisClientParticipation/tree/master/js/strings), and adjusts to whatever language it detects the browser is using. That is not the scope of this feature request.

This has come up in two contexts on Slack:
1. For allowing speakers of other languages to follow the sometimes _very_ interesting Pol.is conversations. (ie. English-speaking understanding Taiwan dynamics) [[Private Chat Context]](https://meta-pol-is.slack.com/archives/software-development/p1477888310000002)
1. For allowing Pol.is to be used by government in jurisdictions with mandatory bilingualism requirements. (ie. Canadian federal gov initiatives) [[Private Chat Context]](https://meta-pol-is.slack.com/archives/conversations/p1480719612000094)

cc @derekhoward @laurawesley

**Comment by mgifford** [comment]
Being able to provide "live" translation would be very good. 

Google is getting better, but for some organization you might actually want to have it translated by people. Lingotek might be able to help here https://www.lingotek.com as I think they have the capacity to do this.

Anyways, definitely support this feature request.

**Comment by colinmegill** [comment]
Great suggestion.

There are a number of combinations I can think of:
1. Rough translation with Google translate
2. Ability of moderator or participants to patch up translations produced
by Google translate
3. Crowd driven translations, with or without improvements or approval by
moderators
4. Translation as a service by a provider such as lingotek

**Comment by patcon** [comment]
This has been added for quite some time (starting here https://github.com/pol-is/polisServer/commit/3eb5ca6f8121897164e3346c1be09b508ce57bcc) so closing out 🎉
