### ISSUE TITLE
Consider renaming this repo

### ISSUE THREAD

**Issue by patcon** [pol-is/polis-issues#75]
Wondering what people think about renaming this repo to more generally point to it as a starting place for contributing :smile_cat: 

I would suggest "overview".

Related: https://github.com/pol-is/issues/issues/67#issuecomment-338029062

## Possible Action Items

- [ ] Rename repo
- [ ] Pin repo prominently in org
- [ ] Give repo a description (with emoji!)

**Comment by metasoarous** [comment]
Again, as mentioned in pol-is/polis-issues#99, if you submit some additional "overview" content (linking to documentation (https://docs.pol.is), deploy etc), I'll make this change.

**Comment by patcon** [comment]
Superseded by https://github.com/pol-is/polis-deploy/issues/8
