### ISSUE TITLE
Missing migration file?

### ISSUE THREAD

**Issue by myguidingstar** [pol-is/polis-issues#87]
I'm trying to set up Polis on my machine. When trying to start poliMath, I got this:
ERROR: column "caching_tick" of relation "math_main" does not exist
I guess some migration file is not updated?

**Comment by colinmegill** [comment]
Thanks for this request. We're working to make the process of installing
pol.is easier, but at the present installing pol.is on your own machine is
unsupported.

**Comment by myguidingstar** [comment]
So I've modified the table with this:
```
ALTER TABLE math_main ADD COLUMN caching_tick bigint;
```
I'm comfortable with Linux, Node and Clojure and can figure out most of the things. After hunting down several errors in the console, I've made all the web apps as well as poliMath up and running.

Thank you for sharing pol.is to the world. The project is what I really want to contribute to.

I still need more time to understand how they work. I'm thinking of low hanging fruits like improving deployment. Please let me know your opinion or plan for that.

**Comment by metasoarous** [comment]
@myguidingstar It sounds like you were ultimately able to figure things out, yes? Did you still have to run that _after_ having run the db migrations as set out in the [updated polisServer README](https://github.com/pol-is/polisServer)?

You may also want to update your checkout of the polisMath repo, and take a peak at the [updated README there](https://github.com/pol-is/polisMath) as well.

Feel free to PR anything wrt deployment. I think you'll need to sign a contributor agreement to get anything in polisServer or polisMath. But feel free to submit to any of the GH wikis, or submit a PR to the new deployment docs repo: https://github.com/pol-is/polisDeployment repo.

**Comment by myguidingstar** [comment]
@metasoarous at that moment, yes. But I haven't caught up with pol-is recently. I've been busy with walkable, a new sql library.
Thanks for your update. Looks like you guys have done a lot since the last time I looked at it

**Comment by patcon** [comment]
@myguidingstar Oh wow! GitHub added a new little pop-up when users hover over usernames, and I just noticed that it says that this was the first issue that you ever opened! That's so cool!

Seems like you're on to something else now, but if you ever come back this way again, we're trying to be way better with helping people get setup :)

It's not an officially sanctioned space at the moment, but if you're around again and looking for help, I'll be in this chat room when I'm at the computer :tada: 
https://gitter.im/polis-overview/Lobby#

**Comment by metasoarous** [comment]
@myguidingstar Lol; That's so funny. I was just looking at walkable! In any case, thanks for the feedback. I'll look to take care of this soon.

**Comment by myguidingstar** [comment]
@patcon lol, actually this is just my new github account. I did stupid things and lost access to the older one.
@metasoarous regarding walkable, you're among the very few who understand both datomic and sql, so you'll get the idea quickly.

**Comment by metasoarous** [comment]
@myguidingstar It looks like this is now in the db setup file:

https://github.com/pol-is/polisServer/blob/master/postgres/db_setup_draft.sql#L796

I'm going to close this for now, but please let me know if you have any other questions. I'd encourage you to join us in https://gitter.im/pol-is/polisDeployment. You're one of the few people who have gotten everything running, so it would be great if we can leverage your experience there to help others get their deployments set up.

**Comment by myguidingstar** [comment]
I havven't caught up with recent updates, but I've joined anyway
