### ISSUE TITLE
Consider re-organizing of github org

### ISSUE THREAD

**Issue by patcon** [pol-is/polis-issues#99]
Having the github org be a good landing page can be helpful. When people arrive on other repos not intended to be starting points, they will often jump back to org to see where they should be. Right now, the github org isn't particularly friendly to newcomers :)

I'll add some facts/feelings and ideas here. (Others should feel free to add their own however they'd prefer.)

**Legend**
:mag: Fact
:heart: Feeling
:bulb: Idea

## Statements

1. :mag: GitHub org's allow ["pinning" important repos](https://blog.github.com/2016-06-16-pin-repositories-to-your-github-profile/)
1. :heart: I feel that other github orgs, like [EDGI's org](https://github.com/edgi-govdata-archiving/), are more welcoming than polis'.
1. :heart: I feel that the "issues" implies a very limited scope.
1. :heart: I feel that repo descriptions are important to helping people orient from the org page.
1. :heart: I feel that a more encompassing top-level meta repo could be better for newcomers and future community-building.
1. :bulb: Let's rename `issues` repo to something wider scope like `overview` (or `polis-hub` or `welcome` or...)
1. :heart: I feel camelcase implies "this is code", and so prefer to avoid it in repo namespacing. (Where other sorts of contributors might be arriving in future.)
1. :bulb: Let's move `polisDeployment` content into `overview`
1. :bulb: Let's add clear descriptions to all repositories.
1. :bulb: Let's pin repos on org page in an intentional order that's helpful for exploration: `overview > polisDocumentation > polisClientAdmin/polisClientParticipation > polisServer > polisMath`

**Comment by patcon** [comment]
Also:

1. :heart: I feel inspired by the Hoodie project's organization of [its GitHub presence](https://github.com/hoodiehq).
1. :heart: I feel positively about emoji kicking off each repo description!

**Comment by colinmegill** [comment]
It's time for all this!

**Comment by patcon** [comment]
Demo! https://github.com/pol-is-2

**Comment by patcon** [comment]
Happy to do the leg-work if you feel like giving me admin ;)

**Comment by metasoarous** [comment]
@patcon I like your overall vision here.

Regarding polisClientParticipation specifically, that code isn't just for the Visualization but for the entire Participation view (the voting widget, etc). In some cases, the visualization might even be turned off. So I'm not in favor of this particular rename.

I'm not apposed to a bit of reorganization around issues/documentation/deployment, but would like to think through things a bit before doing any serious reorganization here.

At the very least though, we can start pinning repos, adding badges, useful descriptions and such as you suggest.

**Comment by metasoarous** [comment]
@patcon How does this look?

![image](https://user-images.githubusercontent.com/88556/39835322-adcd9fa0-5384-11e8-82c3-5ef26a869b24.png)

**Comment by metasoarous** [comment]
@patcon - BTW, I'm open to changing polis-issues to polis-overview with a description like "getting started, feature requests, and bug reports". But we should wait till there's actually some more overview type content there. Happy to accept a PR on that.

**Comment by metasoarous** [comment]
A bit of cleanup: 
![image](https://user-images.githubusercontent.com/88556/39837138-6b07d216-538a-11e8-99d6-ee49aedd3def.png)

**Comment by patcon** [comment]
This was already dealt with, so closing out :)
